### ISSUE TITLE
Excess foreign code

### ISSUE THREAD

**Issue by alexchandel** [michaelficarra/purescript-demo-mario#9]
While an effective demonstration of Signals in purescript, I notice that this example has significant foreign code compared to the [Elm equivalent](http://elm-lang.org/edit/examples/Intermediate/Mario.elm). This would seem to competitively disadvantage the example. Could it be refactored out, or into the Signals library?

**Comment by michaelficarra** [comment]
The foreign code is there because I did not want to make use of a DOM library in this example. I felt it would be more understandable what was going on if less of it was hidden in a DOM library. There's only 4 very special-purpose foreign functions, each of which interact with the DOM (seen in the effect in their type signatures: `Eff (dom :: DOM | eff) Unit`).

**Comment by alexchandel** [comment]
I understand what purescript is. I'm saying the foreign code makes this less readable to people unfamiliar with purescript. It suggests that Purescipt is unwieldy, or incapable of a signals example without copious foreign code. As this example uses signals analogous to Elm's, using a DOM library analogous to Elm's would only make this more understandable.

**Comment by michaelficarra** [comment]
Then if you think that's clearer, I recommend you fork it and use a DOM library instead. Then newcomers will have two resources and can choose to read the one they prefer.

**Comment by alexchandel** [comment]
Haha, but being a newcomer myself I'm afraid I lack the know-how to make Signal-compatible DOM/GUI library.

**Comment by michaelficarra** [comment]
Luckily for you, none of the foreign code depends on the Signal library. You literally only need generic `getElementById`, `setStyle`, `setSrc`, and `onDOMContentLoaded` DOM functions.
